#include "constraints/ConstraintSolver.h"
#include "core/geometry/GeometricTolerance.h"
#include <algorithm>
#include <cmath>
#include <limits>
#include <map>
#include <stdexcept>
#include <type_traits>
namespace microsw::constraints { namespace {
enum class Kind { Line, Circle }; struct Rec { sketch::SketchEntityId id; Kind kind; std::size_t o; };
struct Model { std::vector<Rec> recs; std::map<sketch::SketchEntityId::Value,std::size_t> byId; std::vector<math::Scalar> initial; math::Scalar scale{1}; };
void finite(math::Scalar v){ if(!std::isfinite(v)) throw std::invalid_argument{"non-finite solver value"}; }
std::vector<sketch::SketchElementRef> refs(const sketch::SketchConstraintValue& v){ return std::visit([](const auto& c){using T=std::decay_t<decltype(c)>; if constexpr(std::is_same_v<T,sketch::Horizontal>||std::is_same_v<T,sketch::Vertical>||std::is_same_v<T,sketch::LineLength>) return std::vector{c.line}; else if constexpr(std::is_same_v<T,sketch::CircleRadius>) return std::vector{c.radius}; else return std::vector{c.first,c.second};},v); }
Model modelOf(const sketch::Sketch& s){ Model m; std::map<unsigned,bool> needed; math::Scalar drive{}; for(auto cid:s.constraintIds()){const auto& v=s.findConstraint(cid).value(); for(auto r:refs(v)) needed[r.entity.value()]=true; std::visit([&](const auto& c){using T=std::decay_t<decltype(c)>; if constexpr(std::is_same_v<T,sketch::HorizontalDistance>||std::is_same_v<T,sketch::VerticalDistance>||std::is_same_v<T,sketch::LineLength>||std::is_same_v<T,sketch::CircleRadius>) drive=std::max(drive,std::abs(c.value));},v);} math::Scalar minx=INFINITY,miny=INFINITY,maxx=-INFINITY,maxy=-INFINITY; for(auto id:s.entityIds()){if(!needed.contains(id.value()))continue; const auto&e=s.find(id); auto o=m.initial.size(); if(e.type()==sketch::SketchEntityType::Line){auto&g=std::get<sketch::SketchLine>(e.geometry()).geometry;m.recs.push_back({id,Kind::Line,o});m.initial.insert(m.initial.end(),{g.a().x(),g.a().y(),g.b().x(),g.b().y()});minx=std::min({minx,g.a().x(),g.b().x()});miny=std::min({miny,g.a().y(),g.b().y()});maxx=std::max({maxx,g.a().x(),g.b().x()});maxy=std::max({maxy,g.a().y(),g.b().y()});}else if(e.type()==sketch::SketchEntityType::Circle){auto&g=std::get<sketch::SketchCircle>(e.geometry()).geometry;m.recs.push_back({id,Kind::Circle,o});m.initial.insert(m.initial.end(),{g.center().x(),g.center().y(),g.radius()});minx=std::min(minx,g.center().x()-g.radius());miny=std::min(miny,g.center().y()-g.radius());maxx=std::max(maxx,g.center().x()+g.radius());maxy=std::max(maxy,g.center().y()+g.radius());}else throw std::invalid_argument{"Arc constraints unsupported"};m.byId[id.value()]=m.recs.size()-1;} if(m.initial.empty())throw std::invalid_argument{"no constrained parameters"};m.scale=std::max({math::Scalar{1},std::hypot(maxx-minx,maxy-miny),drive});finite(m.scale);return m;}
const Rec& rec(const Model&m,sketch::SketchEntityId id){auto i=m.byId.find(id.value());if(i==m.byId.end())throw std::invalid_argument{"unparameterized ref"};return m.recs[i->second];}
std::pair<double,double> point(const Model&m,const std::vector<double>&x,sketch::SketchElementRef r){auto&a=rec(m,r.entity);if(a.kind==Kind::Line&&r.kind==sketch::SubElementKind::LineStart)return{x[a.o],x[a.o+1]};if(a.kind==Kind::Line&&r.kind==sketch::SubElementKind::LineEnd)return{x[a.o+2],x[a.o+3]};if(a.kind==Kind::Circle&&r.kind==sketch::SubElementKind::CircleCenter)return{x[a.o],x[a.o+1]};throw std::invalid_argument{"not point ref"};}
std::pair<double,double> dir(const Model&m,const std::vector<double>&x,sketch::SketchElementRef r){auto&a=rec(m,r.entity);if(a.kind!=Kind::Line||r.kind!=sketch::SubElementKind::LineBody)throw std::invalid_argument{"not line ref"};auto dx=x[a.o+2]-x[a.o],dy=x[a.o+3]-x[a.o+1],l=std::hypot(dx,dy);if(!std::isfinite(l)||l<=geometry::defaultGeometricTolerance)throw std::invalid_argument{"degenerate direction"};return{dx/l,dy/l};}
std::vector<double> logical(const sketch::Sketch&s,const Model&m,const std::vector<double>&x){std::vector<double>r;auto len=[&](double v){r.push_back(v/m.scale);};for(auto cid:s.constraintIds())std::visit([&](const auto&c){using T=std::decay_t<decltype(c)>;if constexpr(std::is_same_v<T,sketch::Coincident>){auto[a,b]=point(m,x,c.first);auto[d,e]=point(m,x,c.second);len(d-a);len(e-b);}else if constexpr(std::is_same_v<T,sketch::Horizontal>){(void)dir(m,x,c.line);auto&a=rec(m,c.line.entity);len(x[a.o+3]-x[a.o+1]);}else if constexpr(std::is_same_v<T,sketch::Vertical>){(void)dir(m,x,c.line);auto&a=rec(m,c.line.entity);len(x[a.o+2]-x[a.o]);}else if constexpr(std::is_same_v<T,sketch::Parallel>){auto[a,b]=dir(m,x,c.first);auto[d,e]=dir(m,x,c.second);r.push_back(a*e-b*d);}else if constexpr(std::is_same_v<T,sketch::Perpendicular>){auto[a,b]=dir(m,x,c.first);auto[d,e]=dir(m,x,c.second);r.push_back(a*d+b*e);}else if constexpr(std::is_same_v<T,sketch::HorizontalDistance>){auto[a,b]=point(m,x,c.first);auto[d,e]=point(m,x,c.second);len(d-a-c.value);}else if constexpr(std::is_same_v<T,sketch::VerticalDistance>){auto[a,b]=point(m,x,c.first);auto[d,e]=point(m,x,c.second);len(e-b-c.value);}else if constexpr(std::is_same_v<T,sketch::LineLength>){auto&a=rec(m,c.line.entity);len(std::hypot(x[a.o+2]-x[a.o],x[a.o+3]-x[a.o+1])-c.value);}else{auto&a=rec(m,c.radius.entity);len(x[a.o+2]-c.value);}},s.findConstraint(cid).value());for(auto v:r)finite(v);return r;}
std::vector<double> objective(const sketch::Sketch&s,const Model&m,const std::vector<double>&x,const SolverPolicy&p){auto r=logical(s,m,x);auto w=std::sqrt(p.initialStateRegularization);for(size_t i=0;i<x.size();++i)r.push_back(w*(x[i]-m.initial[i])/m.scale);return r;}
double cost(const std::vector<double>&r){double c=0;for(auto v:r)c+=v*v;finite(c);return c/2;} double maxabs(const std::vector<double>&v){double r=0;for(auto x:v)r=std::max(r,std::abs(x));return r;}
std::vector<std::vector<double>> jac(const sketch::Sketch&s,const Model&m,const std::vector<double>&x,const SolverPolicy&p){auto base=objective(s,m,x,p);std::vector j(base.size(),std::vector<double>(x.size()));for(size_t c=0;c<x.size();++c){auto h=p.finiteDifferenceRelativeStep*std::max({1.0,m.scale,std::abs(x[c])});auto xp=x;auto xm=x;xp[c]+=h;xm[c]-=h;auto rp=objective(s,m,xp,p);auto rm=objective(s,m,xm,p);for(size_t q=0;q<base.size();++q)j[q][c]=(rp[q]-rm[q])/(2*h);}return j;}
bool linear(std::vector<std::vector<double>>a,std::vector<double>b,std::vector<double>&x){auto n=b.size();for(size_t c=0;c<n;++c){size_t p=c;for(size_t r=c+1;r<n;++r)if(std::abs(a[r][c])>std::abs(a[p][c]))p=r;if(!std::isfinite(a[p][c])||std::abs(a[p][c])<1e-18)return false;std::swap(a[p],a[c]);std::swap(b[p],b[c]);for(size_t r=c+1;r<n;++r){auto f=a[r][c]/a[c][c];for(size_t k=c;k<n;++k)a[r][k]-=f*a[c][k];b[r]-=f*b[c];}}x.assign(n,0);for(size_t q=n;q-->0;){auto v=b[q];for(size_t k=q+1;k<n;++k)v-=a[q][k]*x[k];x[q]=v/a[q][q];if(!std::isfinite(x[q]))return false;}return true;}
std::vector<sketch::Sketch::Replacement> rebuild(const Model&m,const std::vector<double>&x){std::vector<sketch::Sketch::Replacement>r;for(auto&a:m.recs)if(a.kind==Kind::Line)r.emplace_back(a.id,sketch::SketchLine{{{x[a.o],x[a.o+1]},{x[a.o+2],x[a.o+3]}}});else r.emplace_back(a.id,sketch::SketchCircle{{{x[a.o],x[a.o+1]},x[a.o+2]}});return r;}
}
ConstraintSolver::ConstraintSolver(SolverPolicy p):policy_(p){if(!(p.stepTolerance>0&&p.costReductionTolerance>0&&p.residualSatisfactionTolerance>0&&p.finiteDifferenceRelativeStep>0&&p.maxIterations&&p.initialDamping>0&&p.dampingAdjustment>1&&p.initialStateRegularization>0))throw std::invalid_argument{"invalid solver policy"};}
SolveResult ConstraintSolver::solve(sketch::Sketch&s)const noexcept{SolveResult out;try{auto m=modelOf(s);auto x=m.initial,res=objective(s,m,x,policy_);auto c=cost(res),d=policy_.initialDamping;out.diagnostics.initialCost=c;for(size_t it=0;it<policy_.maxIterations;++it){out.diagnostics.iterations=it+1;auto j=jac(s,m,x,policy_);size_t n=x.size();std::vector a(n,std::vector<double>(n));std::vector<double>b(n);for(size_t r=0;r<j.size();++r)for(size_t i=0;i<n;++i){b[i]-=j[r][i]*res[r];for(size_t k=0;k<n;++k)a[i][k]+=j[r][i]*j[r][k];}for(size_t i=0;i<n;++i)a[i][i]+=d;std::vector<double>step;if(!linear(a,b,step)){out.status=SolveStatus::NumericalFailure;return out;}if(maxabs(step)<=policy_.stepTolerance)break;auto y=x;for(size_t i=0;i<n;++i)y[i]+=step[i];try{auto yr=objective(s,m,y,policy_);auto yc=cost(yr);if(yc<c){auto reduction=c-yc;x=std::move(y);res=std::move(yr);c=yc;d=std::max(d/policy_.dampingAdjustment,1e-15);if(reduction<=policy_.costReductionTolerance)break;}else d*=policy_.dampingAdjustment;}catch(const std::invalid_argument&){d*=policy_.dampingAdjustment;}}auto lr=logical(s,m,x);out.diagnostics.finalCost=c;out.diagnostics.maxLogicalResidual=maxabs(lr);out.diagnostics.likelyUnderConstrained=lr.size()<x.size();if(out.diagnostics.maxLogicalResidual>policy_.residualSatisfactionTolerance){out.status=SolveStatus::Unsatisfied;return out;}s.replaceMany(rebuild(m,x));out.status=SolveStatus::Solved;}catch(const std::invalid_argument&){out.status=SolveStatus::InvalidInput;}catch(...){out.status=SolveStatus::NumericalFailure;}return out;}
}
